---
- name: enable iptables
  service: name=iptables enabled=yes
  tags: iptables

- name: configure iptables
  template: >
    src=iptables.sysconfig.j2
    dest=/etc/sysconfig/iptables
    owner=root group=root mode=0600
  notify: restart iptables
  tags: iptables
