---
- name: disable firewalld
  service: name=firewalld state=stopped enabled=no
  tags: firewalld

- name: mask firewalld
  command: systemctl mask firewalld
  tags: firewalld

- name: install iptables
  yum: name=iptables-services state=present
  tags: firewalld

- name: enable iptables
  service: name=iptables enabled=yes
  tags: iptables

- name: configure iptables
  template: >
    src=iptables.j2
    dest=/etc/sysconfig/iptables
    owner=root group=root mode=0600
  notify: restart iptables
  tags: iptables
