---
- name: create group
  group: >
    name={{thumbor_group}}
    state=present
  tags: thumbor

- name: create user
  user: >
    name={{thumbor_user}}
    group={{thumbor_group}}
  tags: thumbor

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present enablerepo=epel,remi disable_gpg_check=yes

- name: install dependencies
  yum: name={{item}} state=installed enablerepo=epel,remi disable_gpg_check=yes
  with_items:
    - git
    - python-pip
    - python-devel
    # begin - Thumbor is fairly useless without these
    - libpng
    - libjpeg
    - libpng-devel
    - libjpeg-devel
    - libjasper-devel
    - libwebp-devel
    - ghostscript
    - libtiff
    - libtiff-devel
    - freetype
    - freetype-devel
    - policycoreutils-python # For SEManage
    # end - Thumbor is fairly useless without these
    # GraphicsMagick deps disabled because https://github.com/thumbor/graphicsmagick-engine/issues/4
    - GraphicsMagick-c++-devel
    - boost-devel
  tags: thumbor

- name: upgrade pip for compatibility w/ git
  command: pip install --upgrade pip
  tags: thumbor

- name: install pip dependencies
  pip: >
    name={{item}}
  with_items:
    - pycurl
    - thumbor
    - boto
    - python-dateutil
    - git+https://github.com/willtrking/thumbor_aws.git@{{ thumbor_aws_version }}#egg=thumbor_aws
    # GraphicsMagick deps disabled because https://github.com/thumbor/graphicsmagick-engine/issues/4
    - pgmagick
    - graphicsmagick-engine
    - numpy
  tags: thumbor

- name: copy thumbor conf default
  template: >
    src=thumbor.conf.j2
    dest={{ thumbor_config_file }}
    owner=root
    group=root
    mode=0755
  tags: thumbor
  notify: restart thumbor

- name: copy thumbor key
  template: >
    src=thumbor.key.j2
    dest={{ thumbor_key_file }}
    owner=root
    group=root
    mode=0755
  tags: thumbor

- name: working dir
  file: >
    path={{thumbor_working_directory}}
    owner=root
    group=root
    mode=0644
    state=directory
  tags: thumbor

- name: copy thumbor service start script
  template: >
    src=thumbor-service-start.j2
    dest=/usr/bin/start-thumbor-service
    owner=root
    group=root
    mode=755
  tags: thumbor

- name: sysconfig dir
  file: >
    path=/etc/sysconfig
    owner=root
    group=root
    state=directory
  tags: thumbor

- name: log file
  file: >
    path=/var/log/thumbor.log
    owner={{ thumbor_user}}
    state=touch
  tags: thumbor

- name: copy thumbor sysconfig
  template: >
    src=sysconfig-thumbor.j2
    dest=/etc/sysconfig/thumbor
    owner=root
    group=root
    mode=644
  notify: start thumbor
  tags: thumbor

- name: copy thumbor systemd start script
  template: >
    src=systemd-thumbor.unit.j2
    dest=/etc/systemd/system/thumbor.service
    owner=root
    group=root
    mode=644
  notify: start thumbor
  tags: thumbor

- name: SELinux ports
  command: /usr/sbin/semanage port --add --type http_port_t --proto tcp {{ item }}
  with_items: thumbor_ports
  ignore_errors: True # Will fail if already added
  tags: thumbor

- name: copy nginx config
  template: >
    src=nginx-site.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0755
  notify: restart nginx
  tags: thumbor
